version: '3.7'

services:

  postgres:
    container_name: dagdiezel_postgres
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dagdiezel
      PGDATA: "/data/dagdiezel/postgres"
    volumes:
      - postgres:/data/dagdiezel/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres:



